### ISSUE TITLE
usage: How to connect a textual query to results?

### ISSUE THREAD

**Issue by dcz-self** [fatho/logru#22]
I'm after a system which is used like SQL APIs are used today. I want to implement something like this:

```
let query = universe.prepare_query("config(A, _, _, _).");
for solution in universe.dfs(query) {
   match solution.get_var("A").unwrap() {
     Int(256) => {},
     Sym("mudkipz") => {panic!{};},
     other => {println!(other);},
   }
}
```

But I'm not sure how to extract variables.

There's query.scope with all the variable names and numbers. VarScope doesn't let me iterate over variables directly.

```
    scope: Some(
        VarScope {
            names: [
                Some(
                    "A",
                ),
                None,
                None,
                None,
            ],
        },
    ),
```

Okay, I can traverse query.goals tree. That's awkward, but possible.

But I can't find a way to relate solutions to the results. VarScope treats the variable index as an internal detail and I must refer to the variable by name. Meanwhile, each solution is just a vector with terms matching the variables, no variable names.

How do I know which variable matches which term?

I'm happy to implement anything needed if you point me to which side of the problem you'd like to solve.

**Comment by fatho** [comment]
Good question!

The order of variables in the solution vector aligns with the variable indices (`Var::ord`). So for a given goal variable `v: Var`, you'd find the value at `solution[v.ord()]`.

The REPL example prints solutions with variable names this way:
https://github.com/fatho/logru/blob/78e48cb7aadfc28a07aab59dd4f149439221a112/examples/repl.rs#L165-L186

Note that we only have names here for variables that occur in the query, not for any variables resulting from instantiating goals.

Your use case of indexing the solution by name is not yet so well supported. Currently, `VarScope` only provides `get_or_insert` to translate names to `Var`s, which is a bit inconvenient because you could accidentally create variables. It would probably nice to also have
- `fn get(&self, name: &str) -> Option<Var>`, and like you say, perhaps also:
- `fn iter(&self) -> impl Iterator<Item = Var>`

Then, to get the value of variable `"A"` in the solution, you could do

```rust
let scope = query.scope.as_ref().unwrap();
let var = scope.get("A").unwrap();
let value = solution[var.ord()];
```

It's not as concise yet as `solution.get_var("A")`, but it's a start. The latter is more difficult, since the solver is not supposed to know about names in the current design.

**Comment by dcz-self** [comment]
Thanks, I see now that get_solution even states the relationship between indices and variable ordinals: 

https://docs.rs/logru/latest/logru/search/struct.SolutionIter.html#method.get_solution

I wonder if the solution vector could be its own type to make getting the corresponding variable clearer.

**Comment by fatho** [comment]
> I wonder if the solution vector could be its own type to make getting the corresponding variable clearer.

Yes, I think that would make sense. I can imagine a wrapper type that allows access by `Var` could be useful, then you can write the more obvious:

```rust
let var = scope.get("A").unwrap();
let value = solution.get(var); // instead of solution[var.ord()]
```

It's probably convenient to still have `From` instances converting between the `Vec` representation and the solution wrapper, since there are some tests that check expected solutions by comparing `Vec`s.

For named access, perhaps an abstraction like this would do the trick:

```rust
impl Solution {
    // ...

    pub fn with_scope(&self, scope: &VarScope) -> ScopedSolution<'_> {
        ScopedSolution { solution: self, scope }
    }
}

pub struct ScopedSolution<'a> {
    solution: &'a Solution,
    scope: &'a VarScope,
}

impl<'a> ScopedSolution<'a> {
    pub fn get(&self, var_name: &str) -> Option<Term> {
        let var = scope.get(var_name)?;
        solution.get(var)
    }
}
```

That hides the chaining of first getting the variable by name, and then the solution term by index:

```rust
let solution = solution.with_scope(query.scope.as_ref().unwrap());
let a = solution.get("A");
let b = solution.get("B");
```
